Repository cloudfoundry-incubator/quarks-operator, pull requests merged in 2019-07, with the labels that each got.

#368 CI badges update
  README.md
Labels: unscheduled

#365 Modify debug logging for predicates and events
  pkg/kube/controllers/boshdeployment/bpm_controller.go
  pkg/kube/controllers/boshdeployment/deployment_controller.go
  pkg/kube/controllers/boshdeployment/generated_variable_controller.go
  pkg/kube/controllers/extendedjob/errand_controller.go
  pkg/kube/controllers/extendedjob/job_controller.go
  pkg/kube/controllers/extendedjob/trigger_controller.go
  pkg/kube/util/ctxlog/events.go
Labels: unscheduled

#376 Add phony to build make target
  Makefile
Labels: unscheduled

#371 Re-enable flaky test
  integration/deploy_test.go
  testing/dump_env.sh
Labels: unscheduled

#379 Renamed patches to pre_render_scripts
  integration/deploy_test.go
  pkg/bosh/manifest/containerization.go
  pkg/bosh/manifest/render_job_tmpls.go
  testing/boshmanifest/manifests.go
Labels: unscheduled

#377 Switch back to non-privileged user
  Dockerfile
  pkg/bosh/manifest/container_factory.go
Labels: unscheduled

#372 Handle multi-config files
  pkg/kube/config/fake/fake_clientconfig.go
  pkg/kube/config/getter.go
  pkg/kube/config/getter_test.go
Labels: scheduled

#386 165909121 load affinity struct
  docs/from_bosh_to_kube.md
  go.mod
  pkg/bosh/manifest/container_factory.go
  pkg/bosh/manifest/containerization.go
  pkg/bosh/manifest/containerization/containerization.go
  pkg/bosh/manifest/containerization_test.go
  pkg/bosh/manifest/data_gatherer.go
  pkg/bosh/manifest/data_gatherer_test.go
  pkg/bosh/manifest/desired_manifest.go
  pkg/bosh/manifest/instance_group.go
  pkg/bosh/manifest/job.go
  pkg/bosh/manifest/kube_resources.go
  pkg/bosh/manifest/kube_resources_test.go
  pkg/bosh/manifest/manifest.go
  pkg/bosh/manifest/render_job_tmpls.go
  pkg/bosh/manifest/resolver.go
  pkg/kube/controllers/boshdeployment/bpm_reconciler_test.go
  pkg/kube/controllers/boshdeployment/deployment_reconciler.go
  pkg/kube/controllers/boshdeployment/deployment_reconciler_test.go
  pkg/kube/controllers/boshdeployment/generated_variable_reconciler.go
  testing/assets/gatherManifest.yml
  testing/boshmanifest/manifests.go
  testing/catalog.go
Labels: unscheduled

#383 Add a sidecar that tails all logs in /var/vcap/sys/log
  integration/deploy_test.go
  integration/environment/logs.go
  integration/lifecycle_test.go
  pkg/bosh/manifest/container_factory.go
  pkg/bosh/manifest/container_factory_test.go
  pkg/bosh/manifest/kube_resources_test.go
Labels: in progress

#388 bin/build-image changes
  .dockerignore
  bin/build-image
Labels: unscheduled

#392 Build the charts before running the test storage ginkgo suites
  bin/test-storage
Labels: unscheduled

#391 Support CF_OPERATOR_TESTING_TMP env var for storing the testing logs
  bin/include/testing
  bin/test-cli-e2e
  bin/test-integration
  bin/test-storage
  docs/testing.md
  integration/environment/environment.go
  pkg/testhelper/logger.go
  testing/dump_env.sh
Labels: unscheduled

#397 Versioned cf-operator-base image
  Dockerfile
Labels: unscheduled

#400 Add the ability to freeze failing prestart hook init containers
  .dockerignore
  .gitignore
  Dockerfile
  go.sum
  pkg/bosh/manifest/container_factory.go
  pkg/bosh/manifest/containerization/containerization.go
Labels: unscheduled

#399 Docs improvement
  README.md
  docs/building.md
  docs/development.md
  docs/testing.md
Labels: unscheduled

#396 Separate storage tests for e2e and integration
  .drone.yml
  Makefile
  bin/test-helm-e2e-storage
  bin/test-integration-storage
  docs/testing.md
  pkg/kube/apis/extendedstatefulset/v1alpha1/types.go
Labels: unscheduled

#413 Correct order or resources in examples
  docs/examples/bosh-deployment/boshdeployment-with-custom-variable.yaml
  docs/examples/bosh-deployment/boshdeployment-with-persistent-disk.yaml
  docs/examples/bosh-deployment/boshdeployment.yaml
  testing/boshmanifest/manifests.go
Labels: unscheduled

#416 Remove redundant secret
  docs/examples/bosh-deployment/boshdeployment-with-custom-variable.yaml
  e2e/kube/examples_test.go
Labels: unscheduled

#394 Update development havener file
  dev-env-havener.yaml
Labels: unscheduled

#415 Fix go lint warnings
  pkg/bosh/manifest/containerization/containerization.go
  pkg/bosh/manifest/manifest.go
  pkg/kube/apis/boshdeployment/v1alpha1/types.go
  pkg/kube/controllers/boshdeployment/bpm_reconciler.go
  pkg/kube/util/ctxlog/events.go
  pkg/kube/util/pod/util.go
Labels: unscheduled

#422 Fix implicit variable processing
  docs/examples/bosh-deployment/boshdeployment-with-implicit-variable.yaml
  docs/from_bosh_to_kube.md
  e2e/kube/storage/examples_storage_test.go
  integration/storage/deploy_with_storage_test.go
  pkg/bosh/manifest/interpolate.go
  pkg/bosh/manifest/job_factory.go
  pkg/bosh/manifest/job_factory_test.go
  pkg/bosh/manifest/kube_converter.go
  pkg/bosh/manifest/manifest.go
  pkg/bosh/manifest/resolver.go
  pkg/bosh/manifest/resolver_test.go
  pkg/kube/util/names/names.go
Labels: unscheduled

#427 Implemented spec.IP to be status.podIP
  cmd/internal/trender.go
  e2e/cli/cli_test.go
  e2e/cli/util_render_template_test.go
  pkg/bosh/manifest/container_factory.go
  pkg/bosh/manifest/job_factory.go
  pkg/bosh/manifest/render_job_tmpls.go
  pkg/bosh/manifest/render_job_tmpls_test.go
Labels: unscheduled

#432 Add addon support
  docs/from_bosh_to_kube.md
  pkg/bosh/manifest/addon_placement.go
  pkg/bosh/manifest/addon_placement_test.go
  pkg/bosh/manifest/manifest.go
  pkg/bosh/manifest/resolver.go
  testing/boshmanifest/manifests.go
Labels: unscheduled

#433 Doc fixes
  docs/from_bosh_to_kube.md
  docs/rendering_templates.md
Labels: unscheduled

#435 Increase the timeout from 30s to 60s
  testing/kubectl_helper.go
Labels: unscheduled

#429 Remove unused values from helm values
  cmd/internal/root.go
  deploy/helm/cf-operator/values.yaml
Labels: unscheduled

#431 Remove dead code
  pkg/kube/controllers/boshdeployment/deployment_reconciler.go
  pkg/kube/controllers/extendedjob/errand_controller.go
  pkg/kube/util/finalizer/finalizer.go
  pkg/kube/util/owner/owner.go
  pkg/kube/util/versionedsecretstore/config_names.go
  pkg/kube/util/versionedsecretstore/versioned_secret_store.go
  pkg/kube/util/versionedsecretstore/versioned_secret_store_test.go
Labels: unscheduled

#434 Fix addon links and improve debuggability
  cmd/internal/bpm_configs.go
  cmd/internal/dgather.go
  cmd/internal/root.go
  cmd/internal/trender.go
  cmd/internal/varinterpolation.go
  pkg/bosh/manifest/container_factory.go
  pkg/bosh/manifest/containerization/containerization.go
  pkg/bosh/manifest/data_gatherer.go
  pkg/bosh/manifest/kube_resources.go
  pkg/bosh/manifest/manifest.go
  pkg/bosh/manifest/volume.go
  pkg/kube/controllers/extendedstatefulset/pod_mutator.go
Labels: unscheduled

#439 Speed up havener deployment
  dev-env-havener.yaml
Labels: unscheduled

#437 Changed the flow image to a newly layouted one.
  docs/rendering_templates.md
Labels: scheduled

#447 Refact the data gatherer
  cmd/internal/bpm_configs.go
  cmd/internal/instance_group.go
  docs/commands/cf-operator_util.md
  docs/commands/cf-operator_util_instance-group.md
  docs/controllers/boshdeployment.md
  docs/from_bosh_to_kube.md
  e2e/cli/cli_test.go
  e2e/cli/util_dgather_test.go
  pkg/bosh/converter/job_factory.go
  pkg/bosh/converter/job_factory_test.go
  pkg/bosh/manifest/instance_group_resolver.go
  pkg/bosh/manifest/instance_group_resolver_test.go
  pkg/bosh/manifest/job_provider_links.go
  pkg/kube/controllers/boshdeployment/deployment_reconciler.go
  pkg/kube/controllers/boshdeployment/deployment_reconciler_test.go
Labels: unscheduled

#446 Use sigs.k8s.io/yaml for marshaling/unmarshaling
  cmd/internal/bpm_configs.go
  cmd/internal/instance_group.go
  e2e/cli/util_bpm_configs_test.go
  e2e/cli/util_dgather_test.go
  go.mod
  go.sum
  pkg/bosh/bpm/config.go
  pkg/bosh/converter/container_factory.go
  pkg/bosh/converter/interpolator.go
  pkg/bosh/converter/resolver_test.go
  pkg/bosh/manifest/containerization.go
  pkg/bosh/manifest/containerization_test.go
  pkg/bosh/manifest/instance_group.go
  pkg/bosh/manifest/instance_group_resolver.go
  pkg/bosh/manifest/instance_group_resolver_test.go
  pkg/bosh/manifest/interpolate.go
  pkg/bosh/manifest/job.go
  pkg/bosh/manifest/job_provider_links.go
  pkg/bosh/manifest/manifest.go
  pkg/bosh/manifest/manifest_test.go
  pkg/bosh/manifest/render_job_tmpls.go
  pkg/bosh/manifest/render_job_tmpls_test.go
  pkg/kube/controllers/boshdeployment/bpm_reconciler.go
  pkg/kube/controllers/boshdeployment/bpm_reconciler_test.go
  pkg/kube/controllers/boshdeployment/deployment_reconciler_test.go
  testing/command_helper.go
Labels: unscheduled

#449 Fix freudian typo and clarify example instructions
  README.md
Labels: unscheduled

#448 Remove dead code for trigger jobs
  pkg/kube/controllers/extendedjob/trigger_reconciler.go
Labels: unscheduled

#442 Add the ability to block links
  pkg/bosh/manifest/job_provider_links.go
Labels: unscheduled

#451 Fix int as float bug when rendering
  cmd/internal/instance_group.go
  pkg/bosh/converter/interpolator.go
  pkg/bosh/manifest/containerization.go
  pkg/bosh/manifest/job.go
  pkg/bosh/manifest/manifest.go
  pkg/bosh/manifest/render_job_tmpls_test.go
  testing/assets/ig-resolved.mysql-v1.yml
  testing/assets/jobs-src/pxc/pxc-mysql/templates/drain.sh.erb
Labels: unscheduled, wip

#450 Rename cmd files in manifest package
  e2e/cli/util_instance_group_test.go
  pkg/bosh/manifest/cmd_instance_group_resolver.go
  pkg/bosh/manifest/cmd_instance_group_resolver_test.go
  pkg/bosh/manifest/cmd_interpolate.go
  pkg/bosh/manifest/cmd_interpolate_test.go
  pkg/bosh/manifest/cmd_render_job_tmpls.go
  pkg/bosh/manifest/cmd_render_job_tmpls_test.go
Labels: unscheduled

#458 Improve tail-logs subcmd implementation
  cmd/internal/tlogs.go
  go.mod
  integration/util/util_suite_test.go
Labels: unscheduled

#461 Fixed pre-render scripts execution order
  pkg/bosh/manifest/cmd_instance_group_resolver.go
  pkg/bosh/manifest/cmd_render_job_tmpls.go
Labels: unscheduled

#464 Implemented link(...).address
  go.mod
  pkg/bosh/manifest/cmd_instance_group_resolver.go
  pkg/bosh/manifest/cmd_instance_group_resolver_test.go
  pkg/bosh/manifest/containerization.go
  pkg/bosh/manifest/job_provider_links.go
  testing/assets/jobs-src/loggregator/loggregator_trafficcontroller/templates/bpm.yml.erb
Labels: scheduled
