Repository cloudfoundry-incubator/quarks-operator, pull requests merged in 2019-06, with the labels that each got.

#299 Add history of events in debug mode for:
  pkg/kube/controllers/boshdeployment/bpm_controller.go
  pkg/kube/controllers/boshdeployment/deployment_controller.go
  pkg/kube/controllers/boshdeployment/generated_variable_controller.go
  pkg/kube/controllers/extendedjob/errand_controller.go
  pkg/kube/controllers/extendedjob/job_controller.go
  pkg/kube/controllers/extendedjob/ownership_controller.go
  pkg/kube/controllers/extendedjob/trigger_controller.go
  pkg/kube/util/ctxlog/events.go
Labels: unscheduled

#300 Use webhook readyz route
  pkg/testhelper/wait_for_port.go
Labels: unscheduled

#290 Apply user specified labels and annotations on created resources
  pkg/bosh/manifest/instance_group.go
  pkg/bosh/manifest/kube_resources.go
  pkg/bosh/manifest/kube_resources_test.go
  pkg/bosh/manifest/manifest_test.go
  pkg/kube/controllers/extendedstatefulset/reconciler.go
  testing/boshmanifest/manifests.go
Labels: unscheduled

#304 Remove sub-shell for running cf-operator commands
  pkg/bosh/manifest/container_factory.go
  pkg/bosh/manifest/job_factory.go
  pkg/bosh/manifest/job_factory_test.go
Labels: unscheduled

#308 Skip tests that are taking too long until we fix them
  integration/extended_statefulset_test.go
Labels: unscheduled

#303 Refactor and magic volume strings removal
  cmd/internal/trender.go
  pkg/bosh/manifest/container_factory.go
  pkg/bosh/manifest/container_factory_test.go
  pkg/bosh/manifest/job.go
  pkg/bosh/manifest/job_factory.go
  pkg/bosh/manifest/kube_resources.go
  pkg/bosh/manifest/volume.go
Labels: unscheduled

#310 Updates and reviews for docs
  docs/about_operators.md
  docs/controllers/README.md
  docs/controllers/boshdeployment.md
  docs/controllers/extendedjob.md
  docs/controllers/extendedpersistentvolume.md
  docs/controllers/extendedsecret.md
  docs/controllers/extendedservice.md
  docs/controllers/extendedstatefulset.md
  docs/desired_manifests.md
  docs/development.md
  docs/from_bosh_to_kube.md
  docs/naming.md
  docs/rendering_templates.md
Labels: scheduled

#312 Minikube config file for local dev flow
  dev-env-havener.yaml
Labels: unscheduled

#314 Updated doc to simplify webhook host command
  docs/testing.md
Labels: unscheduled

#319 Allow BPM-less jobs
  pkg/bosh/bpm/config.go
  pkg/bosh/manifest/containerization.go
  pkg/bosh/manifest/data_gatherer.go
Labels: unscheduled

#320 Fix JSON format for event logging of predicates and reconciles
  pkg/kube/util/ctxlog/events.go
Labels: unscheduled

#322 Added chown 1000:1000 cmd for the /var/vcap/...
  docs/from_bosh_to_kube.md
  pkg/bosh/manifest/container_factory.go
  pkg/bosh/manifest/container_factory_test.go
Labels: unscheduled

#324 Revert "Added chown 1000:1000 cmd for the /var/vcap/..."
  docs/from_bosh_to_kube.md
  pkg/bosh/manifest/container_factory.go
  pkg/bosh/manifest/container_factory_test.go
Labels: unscheduled

#325 Set user owner directories
  pkg/bosh/manifest/container_factory.go
  pkg/bosh/manifest/kube_resources.go
Labels: unscheduled

#326 Implement BPM's unsafe.privileged
  docs/from_bosh_to_kube.md
  pkg/bosh/manifest/container_factory.go
Labels: unscheduled

#328 Make job names more readable
  integration/extended_job_test.go
  pkg/bosh/manifest/job_factory.go
  pkg/kube/controllers/boshdeployment/deployment_reconciler_test.go
  pkg/kube/controllers/extendedjob/trigger_reconciler_test.go
  pkg/kube/util/names/names.go
  pkg/kube/util/names/names_test.go
Labels: unscheduled

#330 EJob versioned secrets triggers
  integration/deploy_test.go
  integration/extended_job_test.go
  pkg/bosh/manifest/kube_resources.go
  pkg/kube/controllers/boshdeployment/bpm_controller.go
  pkg/kube/controllers/boshdeployment/deployment_reconciler.go
  pkg/kube/controllers/extendedjob/errand_controller.go
  pkg/kube/controllers/extendedjob/errand_reconciler.go
  pkg/kube/util/names/names.go
  pkg/kube/util/reference/reconciles.go
  pkg/kube/util/versionedsecretstore/versioned_secret.go
  pkg/kube/util/versionedsecretstore/versioned_secret_store.go
Labels: wip

#333 Fix failing unit test after merge
  pkg/kube/controllers/boshdeployment/deployment_reconciler_test.go
Labels: unscheduled

#335 Fixes for EJob reconciliation and tests
  integration/deploy_test.go
  pkg/kube/controllers/extendedjob/errand_controller.go
  pkg/kube/controllers/extendedjob/errand_reconciler.go
  pkg/kube/controllers/extendedjob/job_controller.go
  pkg/kube/controllers/extendedjob/trigger_controller.go
Labels: unscheduled

#336 Allow underscores in instance group name
  integration/deploy_test.go
  pkg/bosh/manifest/container_factory.go
  pkg/bosh/manifest/job_factory.go
  pkg/bosh/manifest/kube_resources.go
  pkg/bosh/manifest/kube_resources_test.go
  pkg/kube/apis/extendedjob/v1alpha1/types.go
  pkg/kube/controllers/boshdeployment/bpm_reconciler.go
  pkg/kube/controllers/boshdeployment/bpm_reconciler_test.go
  pkg/kube/controllers/extendedjob/job_reconciler.go
  pkg/kube/util/names/names.go
  pkg/kube/util/pod/util.go
  testing/boshmanifest/manifests.go
  testing/boshreleases/releases.go
  testing/catalog.go
Labels: unscheduled

#331 Refactored JobSpec Consumes and Provides
  pkg/bosh/manifest/data_gatherer.go
  pkg/bosh/manifest/job.go
Labels: unscheduled

#340 Refactor names in container factory
  pkg/bosh/manifest/container_factory.go
Labels: unscheduled

#344 Fix extended sts example
  bin/build-helm
  e2e/kube/examples_test.go
Labels: unscheduled

#343 Cleanup unused funcs and vars
  e2e/kube/suite_test.go
  pkg/bosh/manifest/volume.go
  pkg/kube/controllers/boshdeployment/deployment_reconciler.go
  pkg/kube/controllers/extendedstatefulset/extendedstatefulset_reconciler.go
Labels: unscheduled

#347 Drone test
  .drone.yml
  Dockerfile
  integration/deploy_test.go
  integration/environment/machine.go
  integration/extended_statefulset_test.go
  pkg/bosh/manifest/kube_resources_test.go
  pkg/bosh/manifest/volume.go
Labels: unscheduled

#353 Fixes to tests and versioned secret references
  integration/deploy_test.go
  integration/environment/environment.go
  pkg/kube/controllers/extendedjob/job_reconciler.go
  pkg/kube/util/versionedsecretstore/versioned_secret_store.go
  pkg/kube/util/versionedsecretstore/versioned_secret_store_test.go
Labels: unscheduled

#357 Don't wait for PVCs until cleanup is fixed
  integration/extended_statefulset_test.go
Labels: unscheduled

#359 Fix e2e PVC test and improve BPM process management
  .gitignore
  docs/examples/bosh-deployment/boshdeployment-with-persistent-disk.yaml
  go.mod
  pkg/bosh/manifest/data_gatherer.go
  testing/kubectl_helper.go
Labels: unscheduled

#360 Reduce the number of parallel tests to 3
  bin/test-helm-e2e
  bin/test-integration
Labels: unscheduled

#362 Use one namespace per integration test
  integration/deploy_test.go
  integration/environment/environment.go
  integration/extended_job_test.go
  integration/lifecycle_test.go
  integration/suite_test.go
Labels: unscheduled

#363 Add support for pre-rendering patching
  Dockerfile
  integration/deploy_test.go
  integration/environment/environment.go
  integration/environment/machine.go
  pkg/bosh/manifest/containerization.go
  pkg/bosh/manifest/render_job_tmpls.go
  testing/boshmanifest/manifests.go
Labels: unscheduled
