Repository cloudfoundry-incubator/quarks-operator, pull requests merged in 2019-03, with the labels that each got.

#129 164072419 ig to extended sts jobs
  cmd/internal/root.go
  pkg/bosh/manifest/kube_converter.go
  pkg/bosh/manifest/kube_converter_test.go
  pkg/kube/operator/operator.go
  pkg/kube/operator/operator_test.go
  testing/catalog.go
Labels: unscheduled

#131 Add new subcommands for the cf-operator cli
  cmd/internal/dgather.go
  cmd/internal/trender.go
  cmd/internal/varinterpolation.go
Labels: unscheduled

#133 Replace the first letter of the error messages in manifest package
  pkg/bosh/manifest/kube_converter.go
  pkg/bosh/manifest/resolver.go
Labels: unscheduled

#136 Do not fail when the current git checkout does not provide tags
  bin/include/versioning
Labels: unscheduled

#135 Fix e2e tests
  e2e/cli_test.go
Labels: unscheduled

#138 Reuse existing test namespace if one already exists
  bin/test-integration
Labels: unscheduled

#140 Fix reusing existing test namespaces
  bin/test-integration
Labels: unscheduled

#139 Using minikube is optional
  bin/up
Labels: unscheduled

#145 Include namespace name in webhook config name
  pkg/kube/controllers/controllers.go
  pkg/kube/controllers/controllers_test.go
Labels: unscheduled

#146 Add the ability to lint the bash scripts
  Makefile
  bin/check-scripts
Labels: unscheduled

#151 Run instance groups on deployment manifest creation and fix tests
  Dockerfile-nobuild
  Makefile
  bin/build-nobuild-image
  bin/test-e2e
  bin/test-integration
  bin/up
  cmd/internal/root.go
  cmd/internal/varinterpolation.go
  e2e/cli_test.go
  go.mod
  integration/deploy_test.go
  integration/environment/environment.go
  integration/environment/machine.go
  integration/extended_job_test.go
  integration/extended_secret_test.go
  integration/extended_statefulset_test.go
  integration/lifecycle_test.go
  integration/suite_test.go
  pkg/bosh/manifest/fakes/resolver.go
  pkg/bosh/manifest/kube_converter.go
  pkg/bosh/manifest/kube_converter_test.go
  pkg/bosh/manifest/resolver.go
  pkg/bosh/manifest/resolver_test.go
  pkg/kube/controllers/boshdeployment/reconciler.go
  pkg/kube/controllers/boshdeployment/reconciler_test.go
  pkg/kube/controllers/controllers.go
  pkg/kube/controllers/extendedjob/errand_reconciler.go
  pkg/kube/controllers/extendedjob/trigger_reconciler.go
  pkg/kube/controllers/extendedstatefulset/pod_mutator.go
  pkg/kube/controllers/extendedstatefulset/reconciler.go
  pkg/kube/controllers/extendedstatefulset/reconciler_test.go
  pkg/kube/controllers/fakes/client.go
  pkg/kube/operator/operator.go
  pkg/kube/operator/operator_test.go
  pkg/testhelper/test_helper.go
  pkg/testhelper/wait_for_port.go
  testing/catalog.go
Labels: unscheduled

#154 Use the default storage class in tests
  integration/environment/environment.go
  integration/environment/machine.go
  integration/extended_statefulset_test.go
  integration/suite_test.go
  testing/catalog.go
Labels: unscheduled

#155 use testhelper pointers
  integration/environment/environment.go
  integration/extended_secret_test.go
  integration/extended_statefulset_test.go
  integration/suite_test.go
  pkg/credsgen/in_memory_generator/certificate_test.go
  pkg/credsgen/in_memory_generator/in_memory_generator_test.go
  pkg/credsgen/in_memory_generator/password_test.go
  pkg/credsgen/in_memory_generator/rsa_key_test.go
  pkg/credsgen/in_memory_generator/ssh_key_test.go
  pkg/kube/controllers/extendedjob/errand_reconciler_test.go
  pkg/kube/controllers/extendedjob/trigger_reconciler.go
  pkg/kube/controllers/extendedjob/trigger_reconciler_test.go
  pkg/testhelper/logger.go
  pkg/testhelper/randomstring.go
  pkg/testhelper/test_helper.go
  testing/catalog.go
Labels: unscheduled

#153 change dev build scripts
  .dockerignore
  .envrc
  Makefile
  bin/up
Labels: unscheduled

#152 Extended Job Restart Auto Errands
  bin/gen-fakes
  docs/controllers/extendedjob.md
  docs/examples/configs.yaml
  docs/examples/exjob_auto-errand-updating.yaml
  integration/environment/machine.go
  integration/extended_job_test.go
  pkg/kube/apis/extendedjob/v1alpha1/types.go
  pkg/kube/controllers/controllers.go
  pkg/kube/controllers/extendedjob/errand_controller.go
  pkg/kube/controllers/extendedjob/errand_reconciler.go
  pkg/kube/controllers/extendedjob/errand_reconciler_test.go
  pkg/kube/controllers/extendedjob/job_controller.go
  pkg/kube/controllers/extendedjob/job_reconciler.go
  pkg/kube/controllers/extendedjob/job_reconciler_test.go
  pkg/kube/controllers/extendedjob/ownership_controller.go
  pkg/kube/controllers/extendedjob/ownership_reconciler.go
  pkg/kube/controllers/extendedjob/ownership_reconciler_test.go
  pkg/kube/controllers/extendedjob/trigger_controller.go
  pkg/kube/controllers/extendedjob/trigger_reconciler.go
  pkg/kube/controllers/fakes/owner.go
  pkg/kube/util/owner/owner.go
  testing/catalog.go
Labels: unscheduled

#156 Add information about setting up the test environment
  docs/testing.md
Labels: in progress

#157 Ensure only yaml is used for the data gathering
  cmd/internal/dgather.go
  cmd/internal/dgather_test.go
  go.mod
  pkg/bosh/manifest/manifest.go
Labels: unscheduled

#158 Mm/remove long wait
  .envrc
Labels: unscheduled, wip

#161 Fix BOSHDepleyment integration test cases
  integration/deploy_test.go
  integration/environment/machine.go
  integration/lifecycle_test.go
Labels: unscheduled

#163 Copy release files to a shared directory in init containers
  pkg/bosh/manifest/kube_converter.go
  pkg/bosh/manifest/kube_converter_test.go
Labels: unscheduled

#169 Try to fix flaky tests
  integration/extended_statefulset_test.go
  pkg/kube/controllers/extendedstatefulset/reconciler.go
Labels: unscheduled

#166 Support self-signed CA variables
  docs/controllers/extendedsecret.md
  docs/controllers/extendedstatefulset.md
  docs/examples/boshdeployment.yaml
  integration/extended_secret_test.go
  pkg/bosh/manifest/kube_converter.go
  pkg/credsgen/in_memory_generator/certificate.go
  pkg/credsgen/in_memory_generator/certificate_test.go
  pkg/kube/controllers/extendedjob/ownership_controller.go
  pkg/kube/controllers/extendedsecret/reconciler.go
  pkg/kube/controllers/webhook_configuration.go
Labels: unscheduled

#171 Set temp manifest ownerReference
  pkg/kube/controllers/boshdeployment/reconciler.go
Labels: unscheduled

#167 Add cfoperator as entrypoint
  Dockerfile
  pkg/kube/controllers/boshdeployment/reconciler.go
Labels: wip

#175 Fix BOSHDeployment reconcile
  cmd/internal/varinterpolation.go
  e2e/cli_test.go
  pkg/bosh/manifest/kube_converter.go
  pkg/kube/apis/boshdeployment/v1alpha1/types.go
  pkg/kube/controllers/boshdeployment/reconciler.go
Labels: unscheduled

#176 Working data gathering phase
  Dockerfile
  Dockerfile-nobuild
  cmd/internal/dgather.go
  cmd/internal/varinterpolation.go
  e2e/cli_test.go
  pkg/bosh/manifest/kube_converter.go
  pkg/bosh/manifest/secret_types.go
  pkg/kube/controllers/boshdeployment/reconciler.go
Labels: unscheduled
