Repository cloudfoundry-incubator/quarks-operator, pull requests merged in 2019-12, with the labels that each got.

#728 Switch from apps/v1beta2 to apps/v1
  pkg/bosh/converter/bpm_resources.go
  pkg/kube/apis/quarksstatefulset/v1alpha1/types.go
  pkg/kube/controllers/quarksstatefulset/quarksstatefulset_controller.go
  pkg/kube/controllers/quarksstatefulset/quarksstatefulset_reconciler.go
  pkg/kube/controllers/quarksstatefulset/quarksstatefulset_reconciler_test.go
  pkg/kube/controllers/quarksstatefulset/util.go
  pkg/kube/controllers/statefulset/statefulset_emulation_test.go
  pkg/kube/controllers/statefulset/statefulset_rollout_controller.go
  pkg/kube/controllers/statefulset/statefulset_rollout_reconciler.go
  pkg/kube/controllers/statefulset/statefulset_rollout_reconciler_test.go
  pkg/kube/controllers/statefulset/statefulset_rollout_util.go
  pkg/kube/controllers/statefulset/statefulset_rollout_util_test.go
  pkg/kube/controllers/statefulset/statefulset_webhook.go
  pkg/kube/controllers/statefulset/statefulset_webhook_test.go
  pkg/kube/util/mutate/mutate.go
  pkg/kube/util/mutate/mutate_test.go
  testing/catalog.go
Labels: unscheduled

#732 Rename ExtendedStatefulSet to QuarksStatefulSet
  pkg/bosh/converter/bpm_resources_test.go
  pkg/kube/controllers/statefulset/statefulset_rollout_reconciler.go
  pkg/kube/controllers/statefulset/statefulset_rollout_reconciler_test.go
  pkg/kube/controllers/statefulset/statefulset_rollout_util_test.go
Labels: unscheduled

#745 Re-enable update watch, to generate 'variable' secrets
  go.mod
  go.sum
  integration/deploy_test.go
  pkg/bosh/converter/job_factory.go
  pkg/kube/controllers/boshdeployment/deployment_reconciler.go
  pkg/kube/controllers/boshdeployment/generated_variable_controller.go
  pkg/kube/controllers/boshdeployment/generated_variable_reconciler_test.go
  pkg/kube/util/reference/reconciles.go
  testing/boshmanifest/manifests.go
Labels: unscheduled

#714 Add missing steps to run integration tests on minikube.
  docs/testing.md
Labels: scheduled

#747 Only useServiceReference is a global helm chart value
  deploy/helm/cf-operator/README.md
  deploy/helm/cf-operator/templates/operator.yaml
  deploy/helm/cf-operator/templates/service.yaml
  deploy/helm/cf-operator/values.yaml
Labels: unscheduled

#751 Remove spamming from the wait command
  cmd/internal/wait.go
Labels: unscheduled

#752 Added configurable wait interval default to 1
  cmd/internal/wait.go
Labels: unscheduled

#753 Update on 'quarks.ports' change
  integration/deploy_test.go
  integration/environment/service.go
  pkg/bosh/bpm/config.go
  pkg/bosh/manifest/cmd_instance_group_resolver.go
  pkg/bosh/manifest/cmd_instance_group_resolver_test.go
  testing/boshmanifest/manifests_unit_only.go
Labels: unscheduled

#758 Bump quarks-job
  bin/include/dependencies
  go.mod
  go.sum
  integration/environment/quarks_job_cmd.go
  integration/storage/suite_test.go
  integration/suite_test.go
Labels: wip
