Repository cloudfoundry-incubator/quarks-operator, pull requests merged in 2019-05, with the labels that each got.

#224 Initial logs are not self-explanatory
  cmd/internal/root.go
Labels: unscheduled

#225 Move to perl instead of sed for inline replacement
  bin/build-helm
Labels: unscheduled

#227 Update logo
  docs/cf-operator-logo.png
Labels: unscheduled

#223 Docs updates
  README.md
  cmd/internal/root.go
  deploy/helm/cf-operator/templates/operator.yaml
  docs/commands/cf-operator.md
  docs/commands/cf-operator_util.md
  docs/commands/cf-operator_util_data-gather.md
  docs/commands/cf-operator_util_template-render.md
  docs/commands/cf-operator_util_variable-interpolation.md
  docs/commands/cf-operator_version.md
  docs/testing.md
  e2e/cli_test.go
  integration/environment/environment.go
Labels: scheduled

#231 e2e tests for cli
  e2e/suite_test.go
  e2e/util_dgather_test.go
  e2e/util_render_template_test.go
  pkg/bosh/manifest/data_gatherer.go
  pkg/bosh/manifest/render_job_tmpls.go
  pkg/bosh/manifest/render_job_tmpls_test.go
Labels: unscheduled

#235 Compress cf-operator helm chart with tar
  bin/build-helm
Labels: unscheduled

#236 Fix slack channel
  README.md
Labels: unscheduled

#226 Add doc about the BOSHDeployment controller
  docs/controllers/boshdeployment.md
Labels: scheduled, wip

#232 Working deployment with a nats consumer
  docs/commands/cf-operator_util.md
  integration/environment/machine.go
  integration/lifecycle_test.go
  pkg/bosh/manifest/kube_converter.go
  pkg/kube/controllers/boshdeployment/deployment_reconciler.go
  pkg/kube/controllers/extendedstatefulset/pod_mutator.go
  testing/catalog.go
Labels: unscheduled

#238 Add `triggering-pod` label on job pods
  docs/controllers/extendedjob.md
  integration/environment/machine.go
  pkg/kube/apis/extendedjob/v1alpha1/types.go
  pkg/kube/controllers/extendedjob/errand_reconciler.go
  pkg/kube/controllers/extendedjob/job_controller.go
  pkg/kube/controllers/extendedjob/trigger_reconciler.go
  pkg/kube/util/names/names.go
Labels: scheduled

#240 Extract data gathering and var interpolation jobs into a factory
  pkg/bosh/manifest/job_factory.go
  pkg/bosh/manifest/job_factory_test.go
  pkg/bosh/manifest/kube_converter.go
  pkg/bosh/manifest/kube_converter_test.go
Labels: scheduled

#243 Skipping pvc tests until CI is fixed
  integration/extended_statefulset_test.go
Labels: accepted

#242 Improvements in the helm chart definition
  bin/build-helm
  deploy/helm/cf-operator/templates/operator.yaml
  deploy/helm/cf-operator/values.yaml
Labels: unscheduled

#244 Refactor manifest and kube converter
  integration/extended_statefulset_test.go
  pkg/bosh/manifest/containerization.go
  pkg/bosh/manifest/docker_image.go
  pkg/bosh/manifest/instance_group.go
  pkg/bosh/manifest/job.go
  pkg/bosh/manifest/job_factory.go
  pkg/bosh/manifest/kube_converter.go
  pkg/bosh/manifest/kube_converter_test.go
  pkg/bosh/manifest/manifest.go
  pkg/kube/controllers/boshdeployment/deployment_reconciler.go
Labels: unscheduled

#246 Fix integration test
  integration/environment/machine.go
  integration/extended_statefulset_test.go
Labels: unscheduled, wip

#251 Enable pvc tests
  integration/extended_statefulset_test.go
Labels: unscheduled

#252 Improved error reporting in end2end tests
  e2e/kube/examples_test.go
  testing/kubectl_helper.go
Labels: unscheduled

#254 Fixed MigratedFrom to be a slice
  pkg/bosh/manifest/instance_group.go
Labels: scheduled

#253 Used .Values.image.pullPolicy appropriately
  deploy/helm/cf-operator/templates/operator.yaml
Labels: scheduled

#257 Fix flake unit test
  pkg/bosh/manifest/kube_converter_test.go
Labels: unscheduled

#259 Bump bosh-template-go to fix a problem with empty links
  go.mod
  pkg/bosh/manifest/render_job_tmpls_test.go
  testing/assets/ig-resolved.mysql-v1.yml
  testing/assets/jobs-src/pxc/pxc-mysql/job.MF
  testing/assets/jobs-src/pxc/pxc-mysql/monit
  testing/assets/jobs-src/pxc/pxc-mysql/templates/bpm.yml.erb
  testing/assets/jobs-src/pxc/pxc-mysql/templates/drain.sh.erb
Labels: unscheduled

#260 Add coverage make target into the Makefile
  Makefile
Labels: unscheduled

#263 Move CLI e2e tests into `e2e/cli` and rename scripts
  Makefile
  bin/test-cli-e2e
  bin/test-helm-e2e
  docs/development.md
  docs/testing.md
  e2e/cli/cli_test.go
  e2e/cli/suite_test.go
  e2e/cli/util_bpm_configs_test.go
  e2e/cli/util_dgather_test.go
  e2e/cli/util_render_template_test.go
  e2e/cli/util_variable_interpolation_test.go
  e2e/kube/suite_test.go
Labels: unscheduled

#262 Embed the ca which was used for generating the cert
  pkg/kube/controllers/extendedsecret/reconciler.go
  pkg/kube/controllers/extendedsecret/reconciler_test.go
Labels: unscheduled

#267 Run integration tests in parallel
  bin/test-integration
  integration/environment/environment.go
  integration/environment/machine.go
  integration/suite_test.go
  pkg/kube/controllers/controllers_test.go
  pkg/kube/controllers/webhook_configuration.go
  pkg/testhelper/logger.go
Labels: unscheduled

#266 Define a readinessProbe endpoint for the cf-operator
  deploy/helm/cf-operator/templates/operator.yaml
  pkg/kube/controllers/controllers.go
Labels: unscheduled

#273 Collect debug info about the kube cluster state on test failures
  e2e/kube/suite_test.go
  integration/suite_test.go
  testing/dump_env.sh
Labels: unscheduled

#276 Use v1 minimum version for secret to avoid race
  e2e/kube/examples_test.go
  pkg/kube/util/names/names.go
Labels: unscheduled

#277 Don't use env in e2e tests
  e2e/kube/suite_test.go
Labels: unscheduled

#278 Removed Kubernetes module
  go.mod
  integration/environment/machine.go
  pkg/kube/controllers/extendedjob/pod_state.go
  pkg/kube/controllers/extendedjob/trigger_reconciler.go
  pkg/kube/controllers/extendedstatefulset/reconciler.go
  pkg/kube/controllers/extendedstatefulset/volumes.go
  pkg/kube/util/pod/util.go
Labels: unscheduled

#281 Labels and Annotations on created resources
  pkg/bosh/manifest/job_factory.go
  pkg/bosh/manifest/job_factory_test.go
  pkg/bosh/manifest/kube_converter.go
  pkg/bosh/manifest/kube_converter_test.go
  pkg/bosh/manifest/kube_resources.go
  pkg/bosh/manifest/kube_resources_test.go
  pkg/kube/controllers/boshdeployment/bpm_reconciler.go
Labels: unscheduled

#283 Improve e2e tests
  bin/test-helm-e2e
  e2e/kube/examples_test.go
  e2e/kube/suite_test.go
Labels: unscheduled

#284 Improvements to integration tests
  bin/build-image
  bin/test-integration
  integration/suite_test.go
  pkg/kube/controllers/extendedjob/trigger_reconciler.go
  pkg/kube/util/pod/util.go
Labels: unscheduled

#286 Add job dirs for /var/vcap/sys
  bin/gen-fakes
  pkg/bosh/manifest/container_factory.go
  pkg/bosh/manifest/container_factory_test.go
  pkg/bosh/manifest/fakes/release_image_provider.go
  pkg/bosh/manifest/job.go
  pkg/bosh/manifest/kube_resources.go
Labels: unscheduled

#287 Also describe Extended* in the dump_env.sh script
  testing/dump_env.sh
Labels: unscheduled

#288 Add missing volume mount on bpm container
  pkg/bosh/manifest/container_factory.go
  pkg/bosh/manifest/container_factory_test.go
Labels: unscheduled

#282 Adding code improvements based on staticcheck
  integration/deploy_test.go
  integration/environment/environment.go
  integration/environment/machine.go
  integration/extended_job_test.go
  integration/extended_statefulset_test.go
  pkg/bosh/manifest/container_factory.go
  pkg/bosh/manifest/data_gatherer.go
  pkg/bosh/manifest/lookup.go
  pkg/bosh/manifest/manifest_test.go
  pkg/bosh/manifest/resolver.go
  pkg/credsgen/in_memory_generator/certificate.go
  pkg/kube/apis/extendedstatefulset/v1alpha1/types.go
  pkg/kube/controllers/boshdeployment/bpm_reconciler_test.go
  pkg/kube/controllers/boshdeployment/deployment_reconciler_test.go
  pkg/kube/controllers/boshdeployment/generated_variable_controller.go
  pkg/kube/controllers/boshdeployment/generated_variable_reconciler_test.go
  pkg/kube/controllers/controllers_test.go
  pkg/kube/controllers/extendedjob/errand_controller.go
  pkg/kube/controllers/extendedjob/job_controller.go
  pkg/kube/controllers/extendedjob/job_reconciler_test.go
  pkg/kube/controllers/extendedjob/ownership_controller.go
  pkg/kube/controllers/extendedjob/query.go
  pkg/kube/controllers/extendedjob/trigger_controller.go
  pkg/kube/controllers/extendedsecret/reconciler_test.go
  pkg/kube/controllers/extendedstatefulset/pod_mutator.go
  pkg/kube/controllers/extendedstatefulset/reconciler.go
  pkg/kube/controllers/extendedstatefulset/volumes.go
  pkg/kube/util/reference/configmap_references.go
  pkg/kube/util/reference/reconciles.go
  pkg/kube/util/reference/secret_references.go
  pkg/kube/util/versionedsecretstore/versioned_secret_store_test.go
Labels: unscheduled

#289 Should not get Secret data through write-only StringData
  pkg/kube/controllers/boshdeployment/bpm_reconciler.go
  pkg/kube/controllers/boshdeployment/generated_variable_reconciler.go
  pkg/kube/controllers/boshdeployment/generated_variable_reconciler_test.go
Labels: unscheduled

#293 Add short forms for the plural versions of our CRDs (ejobs,esecs,bdpls)
  deploy/helm/cf-operator/templates/fissile_v1alpha1_boshdeployment_crd.yaml
  deploy/helm/cf-operator/templates/fissile_v1alpha1_extendedjob_crd.yaml
  deploy/helm/cf-operator/templates/fissile_v1alpha1_extendedsecret_crd.yaml
Labels: unscheduled

#292 Update go modules
  go.mod
Labels: unscheduled

#295 Enable --flakeAttempts ginkgo flag to help with flaky tests
  bin/test-helm-e2e
  bin/test-integration
Labels: unscheduled

#296 Convert resources for each bpm config
  pkg/bosh/manifest/kube_resources.go
  pkg/bosh/manifest/kube_resources_test.go
  pkg/kube/controllers/boshdeployment/bpm_reconciler.go
Labels: unscheduled

#297 Updated bosh-template-go module
  go.mod
Labels: unscheduled

#298 Don't delete the operator prior to finalizers
  e2e/kube/suite_test.go
  testing/kubectl_helper.go
Labels: unscheduled
