Repository cloudfoundry-incubator/quarks-operator, pull requests merged in 2019-11, with the labels that each got.

#668 Remove unused status fields
  integration/environment/machine_esv1.go
  pkg/kube/apis/boshdeployment/v1alpha1/types.go
  pkg/kube/apis/boshdeployment/v1alpha1/zz_generated.deepcopy.go
  pkg/kube/apis/extendedsecret/v1alpha1/types.go
  pkg/kube/apis/extendedstatefulset/v1alpha1/types.go
  pkg/kube/apis/extendedstatefulset/v1alpha1/zz_generated.deepcopy.go
  pkg/kube/client/clientset/versioned/fake/clientset_generated.go
Labels: scheduled

#681 No longer source .envrc in scripts
  .envrc
  bin/build-helm
  bin/build-image
  bin/test-integration
  bin/up
Labels: unscheduled

#686 Fixed container-run when exit 1
  container-run/pkg/containerrun/containerrun.go
  container-run/pkg/containerrun/containerrun_test.go
Labels: unscheduled

#683 Make helm chart values available to quarks-job
  deploy/helm/cf-operator/README.md
  deploy/helm/cf-operator/templates/NOTES.txt
  deploy/helm/cf-operator/templates/cluster_role.yaml
  deploy/helm/cf-operator/templates/operator.yaml
  deploy/helm/cf-operator/values.yaml
  go.mod
  go.sum
Labels: dependencies

#696 Fix generated dummy-container for volume management
  pkg/kube/controllers/extendedstatefulset/volumes.go
Labels: unscheduled

#704 Add missing predicate logging to bdpl, ests controllers
  pkg/kube/controllers/extendedsecret/extendedsecret_controller.go
  pkg/kube/controllers/extendedstatefulset/statefulset_cleanup_controller.go
Labels: unscheduled

#707 Fix nil job consume issue
  pkg/bosh/manifest/cmd_instance_group_resolver.go
  pkg/bosh/manifest/cmd_instance_group_resolver_test.go
  testing/boshmanifest/manifests.go
  testing/catalog.go
Labels: unscheduled

#705 Fixed unrestricted vol when it matches the restricted prefix
  pkg/bosh/converter/volume_factory.go
Labels: unscheduled

#710 Fix CAs not being signed by the configured CA
  pkg/kube/controllers/quarkssecret/quarkssecret_reconciler.go
  pkg/kube/controllers/quarkssecret/quarkssecret_reconciler_test.go
Labels: unscheduled

#712 Add docker image flag default
  cmd/internal/root.go
  go.mod
  go.sum
Labels: unscheduled

#720 Fix 'set -e' and others get lost when sourcing 'bin/include/versioning'
  bin/include/docker
  bin/include/testing
  bin/include/versioning
  bin/test-integration
Labels: unscheduled

#709 Add dev-env-kind.yml
  dev-env-havener.yaml
  dev-env-kind.yaml
Labels: scheduled

#722 Create a doc with spec details about quarks links
  docs/entanglements.md
Labels: unscheduled
