Repository cloudfoundry-incubator/quarks-operator, pull requests merged in 2020-10, with the labels that each got.

#1163 Update quarks-secret dependency
  go.mod
  go.sum
Labels: unscheduled

#1164 Change the coredns image source and tag
  deploy/helm/cf-operator/values.yaml
Labels: in progress

#1172 Updating quarks-secret sets copied status to false
  pkg/kube/controllers/boshdeployment/deployment_reconciler.go
Labels: bug

#1174 Don't force secret rotation
  pkg/kube/controllers/boshdeployment/deployment_reconciler.go
Labels: unscheduled

#1179 feat: pre-upgrade hook for deleting dm qjobs
  deploy/helm/cf-operator/templates/pre-upgrade-hook.yaml
  deploy/helm/cf-operator/values.yaml
Labels: unscheduled

#1181 fix: pre-upgrade hook args
  deploy/helm/cf-operator/templates/pre-upgrade-hook.yaml
Labels: unscheduled

#1184 fix: invalid characters in pre-upgrade labels
  deploy/helm/cf-operator/templates/pre-upgrade-hook.yaml
Labels: unscheduled

#1187 fix: add preUpgradeHookDockerImage to imagelist
  bin/build-helm
Labels: unscheduled

#1211 Update logo in README
  README.md
Labels: unscheduled

#1180 fix: build-image make target dependency
  Makefile
Labels: unscheduled
