Repository cloudfoundry-incubator/quarks-operator, pull requests merged in 2020-05, with the labels that each got.

#916 Revert "Bump github.com/mitchellh/mapstructure from 1.2.2 to 1.3.0"
  go.mod
  go.sum
Labels: unscheduled

#934 Bump coredns image version
  deploy/helm/cf-operator/values.yaml
Labels: unscheduled

#944 Update s390x Dockerfile
  Dockerfile-s390x
Labels: unscheduled

#943 Change number of parallel nodes to 3
  bin/test-integration
Labels: unscheduled

#954 Add symlinks to shared bin
  bin/gen-kube
  bin/lint
  bin/test-cli-e2e
  bin/test-helm-e2e
  bin/test-integration
  bin/test-unit
  bin/tools
Labels: scheduled

#959 Modify cfo cluster role permissions
  deploy/helm/cf-operator/templates/cluster-role.yaml
Labels: in progress

#956 Grep the quarks-job docker image version out of go.mod
  bin/include/dependencies
Labels: unscheduled
